// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Category struct {
	ID        string      `json:"id"`
	Name      interface{} `json:"name"`
	CreatedAt int64       `json:"created_at"`
}

type Task struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	IsCompleted sql.NullInt64  `json:"is_completed"`
	Priority    sql.NullInt64  `json:"priority"`
	DueDate     sql.NullInt64  `json:"due_date"`
	CategoryID  sql.NullString `json:"category_id"`
	UpdatedAt   int64          `json:"updated_at"`
	CreatedAt   int64          `json:"created_at"`
}
