// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks(
  id,
  title,
  description,
  is_completed,
  priority,
  due_date,
  category_id,
  updated_at,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  strftime('%s', 'now'),
  strftime('%s', 'now')
) RETURNING id, title, description, is_completed, priority, due_date, category_id, updated_at, created_at
`

type CreateTaskParams struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	IsCompleted sql.NullInt64  `json:"is_completed"`
	Priority    sql.NullInt64  `json:"priority"`
	DueDate     sql.NullInt64  `json:"due_date"`
	CategoryID  sql.NullString `json:"category_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.createTaskStmt, createTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsCompleted,
		arg.Priority,
		arg.DueDate,
		arg.CategoryID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsCompleted,
		&i.Priority,
		&i.DueDate,
		&i.CategoryID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteTaskStmt, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, is_completed, priority, due_date, category_id, updated_at, created_at
FROM tasks
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.queryRow(ctx, q.getTaskStmt, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsCompleted,
		&i.Priority,
		&i.DueDate,
		&i.CategoryID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, is_completed, priority, due_date, category_id, updated_at, created_at
FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.query(ctx, q.listTasksStmt, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsCompleted,
			&i.Priority,
			&i.DueDate,
			&i.CategoryID,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    title = ?,
    description = ?,
    is_completed = ?,
    priority = ?,
    due_date = ?,
    category_id = ?
WHERE id = ?
RETURNING id, title, description, is_completed, priority, due_date, category_id, updated_at, created_at
`

type UpdateTaskParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	IsCompleted sql.NullInt64  `json:"is_completed"`
	Priority    sql.NullInt64  `json:"priority"`
	DueDate     sql.NullInt64  `json:"due_date"`
	CategoryID  sql.NullString `json:"category_id"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.updateTaskStmt, updateTask,
		arg.Title,
		arg.Description,
		arg.IsCompleted,
		arg.Priority,
		arg.DueDate,
		arg.CategoryID,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsCompleted,
		&i.Priority,
		&i.DueDate,
		&i.CategoryID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
